# Generated by Django 4.1.4 on 2023-03-14 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrier_Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('owner_name', models.CharField(max_length=256)),
                ('company_registered_email', models.EmailField(max_length=256)),
                ('company_register_mobile', models.BigIntegerField()),
                ('company_GST', models.FileField(max_length=256, upload_to='company_GST')),
            ],
        ),
        migrations.CreateModel(
            name='Channel_Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('owner_name', models.CharField(max_length=256)),
                ('company_registered_address', models.CharField(max_length=256)),
                ('company_registered_email', models.EmailField(max_length=256)),
                ('company_register_mobile', models.BigIntegerField()),
                ('company_id_proof', models.FileField(max_length=256, upload_to='company_id_proof')),
                ('individual_id_proof', models.FileField(max_length=256, upload_to='individual_id_proof')),
                ('company_GST', models.FileField(max_length=256, upload_to='company_GST')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pickup_Name', models.CharField(max_length=256)),
                ('Pickup_Mobile_Number', models.CharField(max_length=10)),
                ('Pickup_Alternate_Mobile_Number', models.CharField(max_length=10)),
                ('Pickup_Address1', models.CharField(max_length=256)),
                ('Pickup_Address2', models.CharField(max_length=256)),
                ('Pickup_Landmark', models.CharField(max_length=256)),
                ('Pickup_City', models.CharField(max_length=256)),
                ('Pickup_Pin_code', models.CharField(max_length=6)),
                ('Delivery_Name', models.CharField(max_length=256)),
                ('Delivery_Mobile', models.CharField(max_length=10)),
                ('Delivery_Alternate_Mobile', models.CharField(max_length=10)),
                ('Delivery_Address1', models.CharField(max_length=256)),
                ('Delivery_Address2', models.CharField(max_length=256)),
                ('Delivery_Landmark', models.CharField(max_length=256)),
                ('Delivery_City', models.CharField(max_length=256)),
                ('Delivery_Pin_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recharge_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('payment_status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3)),
                ('recharge_transaction_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('datetime_of_payment', models.DateTimeField(default=django.utils.timezone.now)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
