# Generated by Django 4.1.4 on 2023-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier_integration',
            name='company_GST',
            field=models.FileField(max_length=256, upload_to='Carrier_Integration_company_GST'),
        ),
        migrations.AlterField(
            model_name='channel_integration',
            name='company_GST',
            field=models.FileField(max_length=256, upload_to='Channel_Integration_company_GST'),
        ),
        migrations.AlterField(
            model_name='channel_integration',
            name='company_id_proof',
            field=models.FileField(max_length=256, upload_to='Channel_Integration_company_id_proof'),
        ),
        migrations.AlterField(
            model_name='channel_integration',
            name='individual_id_proof',
            field=models.FileField(max_length=256, upload_to='Channel_Integration_individual_id_proof'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
